# --- INSTALL THE FF. TO USE ---
# Sorta like a mini Postman

# Name: REST Client
# Id: humao.rest-client
# Description: REST Client for Visual Studio Code
# Version: 0.25.1
# Publisher: Huachao Mao
# VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=humao.rest-client


http://localhost:3000/adminviewsales